global  _maintop
global  ncsv, cret, indir
global  _freopen
global  __iob
global  _setbuf
global  _errBuf
global  _s_opt
global  _w_opt
global  _l_opt
global  _crfFile
global  _crfNameBuf
global  _fatalErr
global  _srcFileArg
global  _strcpy
global  _srcFile
global  _tmpFile
global  _rindex
global  _strcat
global  _crfFp
global  _fopen
global  _prWarning
global  _fprintf
global  _tmpFp
global  _s13_9d28
global  _s13_9d1b
psect   top
_maintop:
global csv
call csv
ld      l,(ix+6)
ld      h,(ix+7)
dec     hl
ld      (ix+6),l
ld      (ix+7),h
ld      l,(ix+8)
ld      h,(ix+9)
inc     hl
inc     hl
ld      (ix+8),l
ld      (ix+9),h
jp      l22
l19:
ld      l,(ix+8)
ld      h,(ix+9)
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
inc     hl
ld      a,(hl)
cp      67
jp      z,l34
cp      69
jp      z,l26
cp      76
jp      z,l32
cp      83
jp      z,l28
cp      87
jp      z,l30
cp      99
jp      z,l34
cp      101
jp      z,l26
cp      108
jp      z,l32
cp      115
jp      z,l28
cp      119
jp      z,l30
l21:
ld      l,(ix+6)
ld      h,(ix+7)
dec     hl
ld      (ix+6),l
ld      (ix+7),h
ld      l,(ix+8)
ld      h,(ix+9)
inc     hl
inc     hl
ld      (ix+8),l
ld      (ix+9),h
dec     hl
dec     hl
l22:
ld      a,(ix+6)
or      (ix+7)
jp      z,l20
ld      l,(ix+8)
ld      h,(ix+9)
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
ld      a,(hl)
cp      45
jp      z,l19
l20:
ld      a,(ix+6)
or      (ix+7)
jp      z,l37
ld      hl,__iob
push    hl
ld      hl,29f
push    hl
ld      l,(ix+8)
ld      h,(ix+9)
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _freopen
pop     bc
pop     bc
pop     bc
ld      a,l
or      h
ld      l,(ix+8)
ld      h,(ix+9)
ld      c,(hl)
inc     hl
ld      b,(hl)
jp      nz,L3
push    bc
ld      hl,39f
push    hl
call    _fatalErr
pop     bc
pop     bc
ld      l,(ix+8)
ld      h,(ix+9)
ld      c,(hl)
inc     hl
ld      b,(hl)
L3:
ld      (_srcFileArg),bc
ld      l,c
ld      h,b
push    hl
ld      hl,_srcFile
push    hl
call    _strcpy
pop     bc
pop     bc
ld      de,1
ld      l,(ix+6)
ld      h,(ix+7)
or      a
sbc     hl,de
jp      z,l39
ld      hl,__iob+8
push    hl
ld      hl,49f
push    hl
ld      l,(ix+8)
ld      h,(ix+9)
inc     hl
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
call    _freopen
pop     bc
pop     bc
pop     bc
ld      a,l
or      h
jp      nz,l39
ld      l,(ix+8)
ld      h,(ix+9)
inc     hl
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
push    bc
ld      hl,59f
push    hl
call    _fatalErr
pop     bc
pop     bc
l39:
ld      de,3
ld      l,(ix+6)
ld      h,(ix+7)
or      a
sbc     hl,de
jp      nz,l41
ld      l,(ix+8)
ld      h,(ix+9)
inc     hl
inc     hl
inc     hl
inc     hl
ld      c,(hl)
inc     hl
ld      b,(hl)
ld      (_tmpFile),bc
jp      l41
l26:
ld      hl,__iob+16
push    hl
ld      hl,19f
push    hl
ld      l,(ix+8)
ld      h,(ix+9)
ld      c,(hl)
inc     hl
ld      b,(hl)
inc     bc
inc     bc
push    bc
call    _freopen
pop     bc
pop     bc
ld      hl,_errBuf
ex      (sp),hl
ld      hl,__iob+16
push    hl
call    _setbuf
pop     bc
pop     bc
jp      l21
l28:
ld      a,1
ld      (_s_opt),a
jp      l21
l30:
ld      a,1
ld      (_w_opt),a
jp      l21
l32:
ld      a,1
ld      (_l_opt),a
jp      l21
l34:
ld      l,(ix+8)
ld      h,(ix+9)
ld      a,(hl)
inc     hl
ld      h,(hl)
ld      l,a
inc     hl
inc     hl
ld      a,(hl)
or      a
jp      z,l35
ld      l,(ix+8)
ld      h,(ix+9)
ld      c,(hl)
inc     hl
ld      b,(hl)
inc     bc
inc     bc
ld      (_crfFile),bc
jp      l21
l35:
ld      hl,_crfNameBuf
ld      (_crfFile),hl
jp      l21
l37:
ld      hl,69f
ld      (_srcFileArg),hl
push    hl
ld      hl,_srcFile
push    hl
call    _strcpy
pop     bc
pop     bc
l41:
ld      hl,(_crfFile)
ld      a,l
or      h
jp      z,l42
ld      a,(hl)
or      a
jp      nz,l43
ld      hl,_crfNameBuf
ld      (_crfFile),hl
ld      hl,_srcFile
push    hl
ld      hl,_crfNameBuf
push    hl
call    _strcpy
pop     bc
ld      l,46
ex      (sp),hl
ld      hl,_crfNameBuf
push    hl
call    _rindex
pop     bc
pop     bc
push    hl
pop     iy
ld      a,l
or      h
jp      z,l44
ld      hl,79f
push    hl
push    iy
call    _strcpy
pop     bc
pop     bc
jp      l43
l44:
ld      hl,89f
push    hl
ld      hl,_crfNameBuf
push    hl
call    _strcat
pop     bc
pop     bc
l43:
ld      hl,99f
push    hl
ld      hl,(_crfFile)
push    hl
call    _fopen
pop     bc
pop     bc
ld      (_crfFp),hl
ld      a,l
or      h
jp      nz,l46
ld      hl,(_crfFile)
push    hl
ld      hl,109f
push    hl
call    _prWarning
pop     bc
pop     bc
jp      l42
l46:
ld      hl,_srcFile
push    hl
ld      hl,119f
push    hl
ld      hl,(_crfFp)
push    hl
call    _fprintf
pop     bc
pop     bc
pop     bc
l42:
ld      hl,129f
push    hl
ld      hl,(_tmpFile)
push    hl
call    _fopen
pop     bc
pop     bc
ld      (_tmpFp),hl
ld      a,l
or      h
jp      nz,l48
ld      hl,(_tmpFile)
push    hl
ld      hl,139f
push    hl
call    _fatalErr
l48:
ld      a,116
ld      (_s13_9d28),a
ld      (_s13_9d1b),a
ld      a,8
ld      hl,_s13_9d28+11
ld      (hl),a
ld      hl,_s13_9d1b+11
ld      (hl),a
ld      de,0
ld      l,e
ld      h,d
ld      (_s13_9d1b+1),de
ld      (_s13_9d1b+3),hl
ld      de,1
ld      (_s13_9d28+1),de
ld      (_s13_9d28+3),hl
jp      cret
global  _sub_07e3
global  _s13SP
global  _s13Stk
global  _s13FreeList
_sub_07e3:
ld      hl,_s13Stk+40
ld      (_s13SP),hl
ld      hl,0
ld      (_s13FreeList),hl
ret
global  _InitHash
global  _hashtab
global  wrelop
global  _SymList
_InitHash:
global csv
call csv
push hl
push hl
ld      (ix+-2),0
ld      (ix+-1),0
jp      l54
l51:
ld      de,_hashtab
ld      l,(ix+-2)
ld      h,(ix+-1)
add     hl,hl
add     hl,hl
add     hl,de
ld      (ix+-4),l
ld      (ix+-3),h
ld      e,l
ld      d,h
inc     hl
inc     hl
ld      (hl),e
inc     hl
ld      (hl),d
dec     hl
dec     hl
dec     hl
ld      (hl),e
inc     hl
ld      (hl),d
ld      l,(ix+-2)
ld      h,(ix+-1)
inc     hl
ld      (ix+-2),l
ld      (ix+-1),h
l54:
ld      de,61
ld      l,(ix+-2)
ld      h,(ix+-1)
call    wrelop
jp      m,l51
ld      hl,_SymList
ld      (_SymList+2),hl
ld      (_SymList),hl
jp      cret
19:
defb    97,0
29:
defb    114,0
39:
defb    99,97,110,39,116,32,111,112,101,110,32,37,115,0
49:
defb    119,0
59:
defb    99,97,110,39,116,32,111,112,101,110,32,37,115,0
69:
defb    40,115,116,100,105,110,41,0
79:
defb    46,99,114,102,0
89:
defb    46,99,114,102,0
99:
defb    97,0
109:
defb    67,97,110,39,116,32,99,114,101,97,116,101,32,120,114,101
defb    102,32,102,105,108,101,32,37,115,0
119:
defb    126,37,115,10,0
129:
defb    119,0
139:
defb    99,97,110,39,116,32,111,112,101,110,32,37,115,0
