xsub
link
 -Ptext=100H,data,bss,top -C100H -Ocgennew.COM \
 zcrtcpm.obj \
 data.obj \
 lex1.obj \
 lex2.obj \
 code.obj \
 sym1.obj \
 sym2.obj \
 sym3.obj \
 cgen1.obj \
 cgen2.obj \
 cgen3.obj \
 tree1.obj \
 tree2.obj \
 tree3.obj \
 local1.obj \
 local2.obj \
 main.obj \
 cgentop.obj \
 libc1.obj \
 libc2.obj \
 libc3.obj \
 malloc.obj \
 libc5.obj \
 setup.obj \
 ctype.obj \
 alloccg.obj
